# Generated by Django 5.1.3 on 2024-11-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbank',
            old_name='password',
            new_name='bankpassword',
        ),
    ]
