# Generated by Django 5.1.3 on 2024-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_registeruser_userbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
