# Generated by Django 5.1.3 on 2024-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_registeruser_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
