# Generated by Django 5.1.3 on 2024-11-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_registeruser_userbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='accountno',
            field=models.CharField(max_length=100),
        ),
    ]
