# Generated by Django 5.1.3 on 2024-11-23 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_validateuser_otp_signupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateuser',
            name='otp',
            field=models.CharField(blank=True, default='9377', max_length=4),
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toaccountno', models.CharField(max_length=100)),
                ('fromaccountno', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('transferred_at', models.DateTimeField(auto_now=True)),
                ('frombank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='frombank', to='api.createbank')),
                ('tobank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobank', to='api.createbank')),
            ],
        ),
    ]
