# Generated by Django 5.1.3 on 2024-12-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_validateuser_otp_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tobank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tobank', to='api.createbank'),
        ),
        migrations.AlterField(
            model_name='validateuser',
            name='otp',
            field=models.CharField(blank=True, default='0900', max_length=4),
        ),
    ]
